apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: {{ .Release.Namespace }}
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS {{ .Values.mysql.auth.database }} 
    CHARACTER SET utf8mb4 
    COLLATE utf8mb4_unicode_ci;
    
    GRANT ALL PRIVILEGES ON {{ .Values.mysql.auth.database }}.* 
    TO '{{ .Values.mysql.auth.username }}'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;