apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
  - name: mysql-port
    port: {{ .Values.mysql.service.port }}
    targetPort: {{ .Values.mysql.service.targetPort }}
  selector:
    app: mysql