apiVersion: v1
kind: Secret
metadata:
  name: kkamji-app-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.mysql.auth.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.mysql.auth.password | b64enc }}
  DATABASE_PORT: {{ "3306" | b64enc }}
  DATABASE_NAME: {{ .Values.mysql.auth.database | b64enc }}
  DATABASE_HOST: {{ printf "mysql.%s.svc.cluster.local" .Release.Namespace | b64enc }}