# values.yaml
nameOverride: ""
fullnameOverride: ""

backend:
  image:
    repository: 376129852049.dkr.ecr.ap-northeast-2.amazonaws.com/kkamji-app-backend
    tag: "3.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  hpa:
    minReplicas: 1
    maxReplicas: 5
    memoryUtilization: 80
    scaleUp:
      stabilizationWindowSeconds: 60
      pods: 2
      periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60
      pods: 2
      periodSeconds: 15

mysql:
  image:
    repository: mysql
    tag: "8"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
    targetPort: 3306
  storage:
    size: 5Gi
    storageClass: gp3
  auth:
    rootPassword: testrootpassword
    username: testuser
    password: testpassword1234
    database: kkamji_app