apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc }}
  mysql-user-id: {{ .Values.mysql.auth.username | b64enc }}
  mysql-user-password: {{ .Values.mysql.auth.password | b64enc }}
  mysql-database-name: {{ .Values.mysql.auth.database | b64enc }}