apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Release.Namespace }}
data:
  my.cnf: |
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci