apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: {{ .Values.backend.hpa.minReplicas }}
  maxReplicas: {{ .Values.backend.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.backend.hpa.memoryUtilization }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.backend.hpa.scaleUp.stabilizationWindowSeconds }}
      selectPolicy: Max
      policies:
      - type: Pods
        value: {{ .Values.backend.hpa.scaleUp.pods }}
        periodSeconds: {{ .Values.backend.hpa.scaleUp.periodSeconds }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.backend.hpa.scaleDown.stabilizationWindowSeconds }}
      selectPolicy: Min
      policies:
      - type: Pods
        value: {{ .Values.backend.hpa.scaleDown.pods }}
        periodSeconds: {{ .Values.backend.hpa.scaleDown.periodSeconds }}