apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: database
spec:
  type: NodePort
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306
    nodePort: 30006
  selector:
    app: mysql
