apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Delete        # PVC 삭제 시 EBS 볼륨도 삭제
volumeBindingMode: WaitForFirstConsumer
